### ISSUE TITLE
Missing Apple/iOS artifacts

### ISSUE THREAD

**Issue by armond-avanes** [stoyan-vuchev/squircle-shape#16]
I see that Apple/iOS targets have been setup in the build scripts, but I can't find any artifacts published for those platforms:
https://mvnrepository.com/artifact/io.github.stoyan-vuchev

Is this on the roadmap?

**Comment by stoyan-vuchev** [comment]
> I see that Apple/iOS targets have been setup in the build scripts, but I can't find any artifacts published for those platforms:
> https://mvnrepository.com/artifact/io.github.stoyan-vuchev
> 
> Is this on the roadmap?

Yes, the artifacts are on the roadmap. Currently, the Apple/iOS artifacts are missing due to incompatibility with the build machine, and I'm currently researching for a workaround.

**Comment by armond-avanes** [comment]
Thanks for your reply. You can use GitHub Actions to do the builds on macOS machines.

**Comment by stoyan-vuchev** [comment]
Thanks for the suggestion. I've just got a Mac and managed to publish the artifacts on the MavenCentral repo. Support for iOS targets is finally here, starting from lib version 2.1.0  🎉
