### ISSUE TITLE
MAKE MULTIPLAT plz

### ISSUE THREAD

**Issue by rom4ster** [stoyan-vuchev/squircle-shape#7]
So there is no reason that I can see  for why you require this library to be an ANDROID ONLY library. 

Please correct me if I am wrong but this is a very convenient to have composable so why not make it available to all users instead of only publishing builds for android users and shutting out other compile targets?

**Comment by stoyan-vuchev** [comment]
> So there is no reason that I can see  for why you require this library to be an ANDROID ONLY library. 
> 
> Please correct me if I am wrong but this is a very convenient to have composable so why not make it available to all users instead of only publishing builds for android users and shutting out other compile targets?

I've already had planned to release a multiplatform variant when Compose Multiplatform 1.6 becomes stable.

Unfortunately, I don't have any Apple devices, and therefore, I'm unable to run tests on iOS and MacOS targets.

**Comment by rom4ster** [comment]
Partial support would be nice for at least desktop targets. Worst case I can just copy paste the classes but thats not a robust solution.

**Comment by stoyan-vuchev** [comment]
I'll try to bring multiplatform support soon. Since the library is compose based, there shouldn't be any issues on different targets.

**Comment by stoyan-vuchev** [comment]
The library now supports Compose Multiplatform and here is what to expect:

- The focus of the library will be on Compose Multiplatform.
- Support for Android-only projects is still there and it will be maintained as well.
- A detailed migration guide from Android projects to Compose Multiplatform projects will be added soon.
